---
http_interactions:
- request:
    method: post
    uri: https://api.basistheory.com/applications
    body:
      encoding: UTF-8
      string: '{"name":"RSpec Test","type":"server_to_server"}'
    headers:
      X-Api-Key:
      - "<NO SOUP FOR YOU>"
      Content-Type:
      - application/json
      User-Agent:
      - Faraday v1.8.0
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json; charset=utf-8
      Location:
      - https://api.basistheory.com/applications/e4842e02-1349-407f-a833-aa34193dce17
      Request-Context:
      - appId=cid-v1:cdb7d2c6-2cbb-43ab-a23f-e8853a5afc9b
      Bt-Trace-Id:
      - fa90e129-a33d-42cc-9f60-4df80ef5e5a4
      X-Xss-Protection:
      - 1; mode=block
      X-Content-Type-Options:
      - nosniff
      Content-Security-Policy:
      - default-src 'self'
      X-Cache:
      - CONFIG_NOCACHE
      X-Azure-Ref:
      - 0JJ1ZYQAAAAC7H1QrkGjUToGSD2cfHnVUQ0hHRURHRTE2MTMAMmM1Nzk0NDgtNjA3MC00MjgyLWIzYWMtZGE3MGQ0NmIxYzQ3
      Date:
      - Sun, 03 Oct 2021 12:08:05 GMT
    body:
      encoding: UTF-8
      string: '{"id":"e4842e02-1349-407f-a833-aa34193dce17","tenant_id":"<NO SOUP
        FOR YOU>","name":"RSpec Test","key":"key_GDeogPpWk7D33rNggYafKC","type":"server_to_server","created_at":"2021-10-03T12:08:05.5418266+00:00","permissions":[]}'
  recorded_at: Sun, 03 Oct 2021 12:08:05 GMT
recorded_with: VCR 6.0.0
