name: Tests

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["2.5", "2.6", "2.7", "3.0"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Rubocop check
      run: bundle exec rubocop

    - name: Run tests
      run: bundle exec rspec
